### ISSUE TITLE
2 box options in settings aren't completly visible

### ISSUE THREAD

**Issue by C3pa** [polemion/Wrye-Mash-Polemos#4]
As can be seen on the picture, 2 options in settings are partially covered so the user can't see them completely

![Scr1](https://user-images.githubusercontent.com/41503714/93048512-58c73e00-f65f-11ea-8912-f24c768f1637.png)

**Comment by polemion** [comment]
Fixed on the upcoming v101beta4.

Thank you for reporting it.
