### ISSUE TITLE
Plugin limit for OpenMW isn't 255

### ISSUE THREAD

**Issue by C3pa** [polemion/Wrye-Mash-Polemos#8]
According to the official [FAQ](https://openmw.org/faq/):

> Support for up to 2147483646 loaded mods (up from 255 in the original Morrowind engine)

Can you consider implementing that?

**Comment by polemion** [comment]
Better late than never. Fixed in the latest commits, but needs testing:
- https://github.com/polemion/Wrye-Mash-Polemos/commit/dbce232bd053ff8e2c49e6ada85c570f07376d7d
- https://github.com/polemion/Wrye-Mash-Polemos/commit/68421a5517e85ae08403e98a9988084682482643
